import { OnboardingData } from "../types";

export const defaultDemoProfile: OnboardingData = {
  name: "Gabriel R.",
  age: 38,
  gender: "male",
  birthCountry: "España",
  province: "Madrid",
  city: "Madrid",
  residenceCountry: "España",
  areaType: "urban",
  civilStatus: "stable_pair",
  childrenCount: 2,
  profession: "Director Ejecutivo de Tecnología",
  educationLevel: "Máster Universitario",
  annualIncome: 120000,
  religion: "Ninguna",
  languages: ["Español", "Inglés"],
  
  height: 180,
  weight: 88,
  waistCircumference: 96,
  systolicPressure: 132,
  diastolicPressure: 84,
  heartRate: 72,
  oxygenSaturation: 98,
  sittingHours: 9,
  standingHours: 2,
  physicalActivityLevel: "moderate",
  vo2Max: 42,
  restingHeartRate: 64,
  
  hypertension: false,
  diabetes: false,
  cholesterol: true,
  cardiovascularDisease: false,
  cancer: false,
  respiratoryDisease: false,
  medication: "Ninguna",
  familyHistory: "Padre con antecedentes de colesterol alto y abuelo con infarto a los 72 años.",
  surgeries: "Apendicectomía a los 14 años",
  allergies: "Polen estacional",
  
  chronicPain: false,
  sleepQuality: "fair",
  sleepHours: 6.5,
  stressLevel: "high",
  ansiedadLevel: "mild",
  depresionLevel: "none",
  
  alcoholConsumption: "moderate",
  smoking: "former",
  vaping: false,
  drugsConsumption: false,
  weeklyExerciseHours: 2,
  nutritionQuality: "average",
  sugarConsumption: "moderate",
  dailyWaterLitres: 1.5,
  caffeineIntake: "high",
  socialMediaHours: 2.5,
  streamingHours: 2.0,
  gamingHours: 0.5,
  readingHoursWeekly: 1,
  meditationMinutesWeekly: 15,
  outdoorHoursWeekly: 3,
  timeWithFriendsHoursWeekly: 4,
  timeWithChildrenHoursWeekly: 8,
  timeWithPartnerHoursWeekly: 10,
  timeWithParentsHoursWeekly: 1,
  timeWithPetsHoursWeekly: 2,
  
  hoursWorkedWeekly: 48,
  workType: "hybrid",
  homeOfficePercentage: 40,
  businessTravelDaysYearly: 12,
  commuteHoursDaily: 1.2,
  vacationDaysYearly: 22,
  financialGoals: "Asegurar un retiro libre de deudas a los 60 años con capital pasivo de $80,000 anuales.",
  desiredRetirementAge: 60
};
